### ISSUE TITLE
Preconditions don't work for a function returning void

### ISSUE THREAD

**Issue by villevoutilainen** [arcosuc3m/clang-contracts#1]
Simple test:

void f(int x)
  [[expects:  x>0]]
{
}

int main()
{
}

The compiler ICEs:

clang-6.0: /home/vivoutil/llvm/contracts/clang-contracts/tools/clang/lib/AST/Type.cpp:1942: bool clang::Type::isConstantSizeType() const: Assertion `!isIncompleteType() && "This doesn't make sense for incomplete types"' failed.
#0 0x000000000406d2cb llvm::sys::PrintStackTrace(llvm::raw_ostream&) /home/vivoutil/llvm/contracts/clang-contracts/lib/Support/Unix/Signals.inc:398:0
#1 0x000000000406d35e PrintStackTraceSignalHandler(void*) /home/vivoutil/llvm/contracts/clang-contracts/lib/Support/Unix/Signals.inc:462:0
#2 0x000000000406b54d llvm::sys::RunSignalHandlers() /home/vivoutil/llvm/contracts/clang-contracts/lib/Support/Signals.cpp:49:0
#3 0x000000000406cb40 SignalHandler(int) /home/vivoutil/llvm/contracts/clang-contracts/lib/Support/Unix/Signals.inc:252:0
#4 0x00007fa1ecb3f390 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x11390)
#5 0x00007fa1ebada428 gsignal /build/glibc-Cl5G7W/glibc-2.23/signal/../sysdeps/unix/sysv/linux/raise.c:54:0
#6 0x00007fa1ebadc02a abort /build/glibc-Cl5G7W/glibc-2.23/stdlib/abort.c:91:0
#7 0x00007fa1ebad2bd7 __assert_fail_base /build/glibc-Cl5G7W/glibc-2.23/assert/assert.c:92:0
#8 0x00007fa1ebad2c82 (/lib/x86_64-linux-gnu/libc.so.6+0x2dc82)
#9 0x00000000074e1140 clang::Type::isConstantSizeType() const /home/vivoutil/llvm/contracts/clang-contracts/tools/clang/lib/AST/Type.cpp:1943:0
#10 0x000000000468d598 clang::CodeGen::CodeGenFunction::EmitAutoVarAlloca(clang::VarDecl const&) /home/vivoutil/llvm/contracts/clang-contracts/tools/clang/lib/CodeGen/CGDecl.cpp:973:0
#11 0x000000000468d1ae clang::CodeGen::CodeGenFunction::EmitAutoVarDecl(clang::VarDecl const&) /home/vivoutil/llvm/contracts/clang-contracts/tools/clang/lib/CodeGen/CGDecl.cpp:927:0
#12 0x0000000004689c4a clang::CodeGen::CodeGenFunction::EmitVarDecl(clang::VarDecl const&) /home/vivoutil/llvm/contracts/clang-contracts/tools/clang/lib/CodeGen/CGDecl.cpp:179:0
#13 0x00000000046899dc clang::CodeGen::CodeGenFunction::EmitDecl(clang::Decl const&) /home/vivoutil/llvm/contracts/clang-contracts/tools/clang/lib/CodeGen/CGDecl.cpp:133:0
#14 0x00000000043bf5c4 clang::CodeGen::CodeGenFunction::EmitDeclStmt(clang::DeclStmt const&) /home/vivoutil/llvm/contracts/clang-contracts/tools/clang/lib/CodeGen/CGStmt.cpp:1133:0
#15 0x00000000043bb4c4 clang::CodeGen::CodeGenFunction::EmitSimpleStmt(clang::Stmt const*) /home/vivoutil/llvm/contracts/clang-contracts/tools/clang/lib/CodeGen/CGStmt.cpp:345:0
#16 0x00000000043ba86f clang::CodeGen::CodeGenFunction::EmitStmt(clang::Stmt const*, llvm::ArrayRef<clang::Attr const*>) /home/vivoutil/llvm/contracts/clang-contracts/tools/clang/lib/CodeGen/CGStmt.cpp:53:0
#17 0x00000000043bb79e clang::CodeGen::CodeGenFunction::EmitCompoundStmtWithoutScope(clang::CompoundStmt const&, bool, clang::CodeGen::AggValueSlot) /home/vivoutil/llvm/contracts/clang-contracts/tools/clang/lib/CodeGen/CGStmt.cpp:379:0
#18 0x000000000443480f clang::CodeGen::CodeGenFunction::EmitFunctionBody(clang::CodeGen::FunctionArgList&, clang::Stmt const*) /home/vivoutil/llvm/contracts/clang-contracts/tools/clang/lib/CodeGen/CodeGenFunction.cpp:1121:0
#19 0x0000000004435446 clang::CodeGen::CodeGenFunction::GenerateCode(clang::GlobalDecl, llvm::Function*, clang::CodeGen::CGFunctionInfo const&) /home/vivoutil/llvm/contracts/clang-contracts/tools/clang/lib/CodeGen/CodeGenFunction.cpp:1286:0
#20 0x000000000445696d clang::CodeGen::CodeGenModule::EmitGlobalFunctionDefinition(clang::GlobalDecl, llvm::GlobalValue*) /home/vivoutil/llvm/contracts/clang-contracts/tools/clang/lib/CodeGen/CodeGenModule.cpp:3383:0
#21 0x00000000044508ae clang::CodeGen::CodeGenModule::EmitGlobalDefinition(clang::GlobalDecl, llvm::GlobalValue*) /home/vivoutil/llvm/contracts/clang-contracts/tools/clang/lib/CodeGen/CodeGenModule.cpp:2027:0
#22 0x000000000444f8fb clang::CodeGen::CodeGenModule::EmitGlobal(clang::GlobalDecl) /home/vivoutil/llvm/contracts/clang-contracts/tools/clang/lib/CodeGen/CodeGenModule.cpp:1804:0
#23 0x000000000445a9f1 clang::CodeGen::CodeGenModule::EmitTopLevelDecl(clang::Decl*) /home/vivoutil/llvm/contracts/clang-contracts/tools/clang/lib/CodeGen/CodeGenModule.cpp:4125:0
#24 0x0000000004ee751d (anonymous namespace)::CodeGeneratorImpl::HandleTopLevelDecl(clang::DeclGroupRef) /home/vivoutil/llvm/contracts/clang-contracts/tools/clang/lib/CodeGen/ModuleBuilder.cpp:159:0
#25 0x0000000004ee07f7 clang::BackendConsumer::HandleTopLevelDecl(clang::DeclGroupRef) /home/vivoutil/llvm/contracts/clang-contracts/tools/clang/lib/CodeGen/CodeGenAction.cpp:170:0
#26 0x0000000005c344e5 HandleTopLevelDecl(clang::ASTConsumer*, clang::Sema&, clang::DeclGroupRef) /home/vivoutil/llvm/contracts/clang-contracts/tools/clang/lib/Parse/ParseAST.cpp:145:0
#27 0x0000000005c34b36 clang::ParseAST(clang::Sema&, bool, bool) /home/vivoutil/llvm/contracts/clang-contracts/tools/clang/lib/Parse/ParseAST.cpp:244:0
#28 0x00000000049bedf5 clang::ASTFrontendAction::ExecuteAction() /home/vivoutil/llvm/contracts/clang-contracts/tools/clang/lib/Frontend/FrontendAction.cpp:999:0
#29 0x0000000004edee5e clang::CodeGenAction::ExecuteAction() /home/vivoutil/llvm/contracts/clang-contracts/tools/clang/lib/CodeGen/CodeGenAction.cpp:1028:0
#30 0x00000000049be80a clang::FrontendAction::Execute() /home/vivoutil/llvm/contracts/clang-contracts/tools/clang/lib/Frontend/FrontendAction.cpp:901:0
#31 0x000000000495b08e clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) /home/vivoutil/llvm/contracts/clang-contracts/tools/clang/lib/Frontend/CompilerInstance.cpp:991:0
#32 0x0000000004b0e343 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) /home/vivoutil/llvm/contracts/clang-contracts/tools/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp:252:0
#33 0x0000000001eed613 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) /home/vivoutil/llvm/contracts/clang-contracts/tools/clang/tools/driver/cc1_main.cpp:221:0
#34 0x0000000001ee26f6 ExecuteCC1Tool(llvm::ArrayRef<char const*>, llvm::StringRef) /home/vivoutil/llvm/contracts/clang-contracts/tools/clang/tools/driver/driver.cpp:309:0
#35 0x0000000001ee3400 main /home/vivoutil/llvm/contracts/clang-contracts/tools/clang/tools/driver/driver.cpp:388:0
#36 0x00007fa1ebac5830 __libc_start_main /build/glibc-Cl5G7W/glibc-2.23/csu/../csu/libc-start.c:325:0
#37 0x0000000001edfd09 _start (/home/vivoutil/llvm/contracts/build/bin/clang-6.0+0x1edfd09)
Stack dump:
0.	Program arguments: /home/vivoutil/llvm/contracts/build/bin/clang-6.0 -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -mrelax-all -disable-free -main-file-name test2.cpp -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -dwarf-column-info -debug-info-kind=limited -dwarf-version=4 -debugger-tuning=gdb -resource-dir /home/vivoutil/llvm/contracts/build/lib/clang/6.0.0 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/x86_64-linux-gnu/c++/5.4.0 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/x86_64-linux-gnu/c++/5.4.0 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/backward -internal-isystem /usr/local/include -internal-isystem /home/vivoutil/llvm/contracts/build/lib/clang/6.0.0/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include --std=c++2a -build-level=default -fdeprecated-macro -fdebug-compilation-dir /home/vivoutil/llvm/contracts -ferror-limit 19 -fmessage-length 80 -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -o /tmp/test2-acdff1.o -x c++ test2.cpp 
1.	test2.cpp:6:1: current parser token 'int'
2.	test2.cpp:1:6: LLVM IR generation of declaration 'f'
3.	test2.cpp:1:6: Generating code for declaration 'f'
clang-6.0: error: unable to execute command: Aborted (core dumped)
clang-6.0: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 6.0.0  (https://github.com/arcosuc3m/clang-contracts.git b39955327a32adc916df6b86120a416f0eb93986)
Target: x86_64-unknown-linux-gnu
Thread model: posix

**Comment by jalopezg-uc3m** [comment]
This was was solved in commit b712feafdbd2091f31f29122bb5f7df7f1fa93ef.

**Comment by villevoutilainen** [comment]
This still doesn't work for templates:

template <class T>
void f(T x)
  [[expects:  x>0]]
{
}

int main()
{
  f(-42);
}

**Comment by jdgarciauc3m** [comment]
Confirmed the issue in the case of template
